version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./env/mosquitto/config:/mosquitto/config
      - ./env/mosquitto/data:/mosquitto/data
      - ./env/mosquitto/log:/mosquitto/log

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mqtt
    environment:
      - MONGODB_URI=mongodb://admin:adminpassword@mongodb:27017
      - MQTT_BROKER=mqtt://mqtt:1883

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: