version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=plts_puskesmas_tanah_toraja
      - MONGO_INITDB_ROOT_PASSWORD=2025_@Puskesmas_P1LT5
  
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=plts_puskesmas_tanah_toraja
      - POSTGRES_PASSWORD=2025_@Puskesmas_P1LT5
      - POSTGRES_DB=plts_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./env/mosquitto/config:/mosquitto/config
      - ./env/mosquitto/data:/mosquitto/data
      - ./env/mosquitto/log:/mosquitto/log
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mqtt
      - postgres
    environment:
      - MONGODB_URI=mongodb://plts_puskesmas_tanah_toraja:2025_%40Puskesmas_P1LT5@mongodb:27017
      - MQTT_BROKER=mqtt://mqtt:1883
      - POSTGRES_URI=postgresql://plts_puskesmas_tanah_toraja:2025_%40Puskesmas_P1LT5@postgres:5432/plts_db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
  postgres_data: